=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module GoodSender
  class Domain < ApiModelBase
    # The domain name.
    attr_accessor :domain

    # Subdomain used for click tracking.
    attr_accessor :tracking

    # Subdomain used for the return path.
    attr_accessor :return_path

    # Whether outbound mail from this domain must be sent over TLS.
    attr_accessor :require_tls

    attr_accessor :verification

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'domain' => :'domain',
        :'tracking' => :'tracking',
        :'return_path' => :'return_path',
        :'require_tls' => :'require_tls',
        :'verification' => :'verification'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'domain' => :'String',
        :'tracking' => :'String',
        :'return_path' => :'String',
        :'require_tls' => :'Boolean',
        :'verification' => :'DomainVerification'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GoodSender::Domain` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GoodSender::Domain`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      else
        self.domain = nil
      end

      if attributes.key?(:'tracking')
        self.tracking = attributes[:'tracking']
      else
        self.tracking = nil
      end

      if attributes.key?(:'return_path')
        self.return_path = attributes[:'return_path']
      else
        self.return_path = nil
      end

      if attributes.key?(:'require_tls')
        self.require_tls = attributes[:'require_tls']
      else
        self.require_tls = nil
      end

      if attributes.key?(:'verification')
        self.verification = attributes[:'verification']
      else
        self.verification = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @domain.nil?
        invalid_properties.push('invalid value for "domain", domain cannot be nil.')
      end

      if @tracking.nil?
        invalid_properties.push('invalid value for "tracking", tracking cannot be nil.')
      end

      if @return_path.nil?
        invalid_properties.push('invalid value for "return_path", return_path cannot be nil.')
      end

      if @require_tls.nil?
        invalid_properties.push('invalid value for "require_tls", require_tls cannot be nil.')
      end

      if @verification.nil?
        invalid_properties.push('invalid value for "verification", verification cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @domain.nil?
      return false if @tracking.nil?
      return false if @return_path.nil?
      return false if @require_tls.nil?
      return false if @verification.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] domain Value to be assigned
    def domain=(domain)
      if domain.nil?
        fail ArgumentError, 'domain cannot be nil'
      end

      @domain = domain
    end

    # Custom attribute writer method with validation
    # @param [Object] tracking Value to be assigned
    def tracking=(tracking)
      if tracking.nil?
        fail ArgumentError, 'tracking cannot be nil'
      end

      @tracking = tracking
    end

    # Custom attribute writer method with validation
    # @param [Object] return_path Value to be assigned
    def return_path=(return_path)
      if return_path.nil?
        fail ArgumentError, 'return_path cannot be nil'
      end

      @return_path = return_path
    end

    # Custom attribute writer method with validation
    # @param [Object] require_tls Value to be assigned
    def require_tls=(require_tls)
      if require_tls.nil?
        fail ArgumentError, 'require_tls cannot be nil'
      end

      @require_tls = require_tls
    end

    # Custom attribute writer method with validation
    # @param [Object] verification Value to be assigned
    def verification=(verification)
      if verification.nil?
        fail ArgumentError, 'verification cannot be nil'
      end

      @verification = verification
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          domain == o.domain &&
          tracking == o.tracking &&
          return_path == o.return_path &&
          require_tls == o.require_tls &&
          verification == o.verification
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [domain, tracking, return_path, require_tls, verification].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
