=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module GoodSender
  # Per-record verification state for the domain. `verified` is the overall flag; the individual `*_verified` fields indicate which DNS records still need attention when `verified` is `false`. 
  class DomainVerification < ApiModelBase
    # Overall verification status. True only when every required DNS record is in place.
    attr_accessor :verified

    # Whether the tracking subdomain CNAME is in place.
    attr_accessor :tracking_verified

    # Whether the return-path subdomain CNAME is in place.
    attr_accessor :return_path_verified

    # Whether the first DKIM record is in place.
    attr_accessor :dkim1_verified

    # Whether the second DKIM record is in place.
    attr_accessor :dkim2_verified

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'verified' => :'verified',
        :'tracking_verified' => :'tracking_verified',
        :'return_path_verified' => :'return_path_verified',
        :'dkim1_verified' => :'dkim1_verified',
        :'dkim2_verified' => :'dkim2_verified'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'verified' => :'Boolean',
        :'tracking_verified' => :'Boolean',
        :'return_path_verified' => :'Boolean',
        :'dkim1_verified' => :'Boolean',
        :'dkim2_verified' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GoodSender::DomainVerification` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GoodSender::DomainVerification`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      else
        self.verified = nil
      end

      if attributes.key?(:'tracking_verified')
        self.tracking_verified = attributes[:'tracking_verified']
      else
        self.tracking_verified = nil
      end

      if attributes.key?(:'return_path_verified')
        self.return_path_verified = attributes[:'return_path_verified']
      else
        self.return_path_verified = nil
      end

      if attributes.key?(:'dkim1_verified')
        self.dkim1_verified = attributes[:'dkim1_verified']
      else
        self.dkim1_verified = nil
      end

      if attributes.key?(:'dkim2_verified')
        self.dkim2_verified = attributes[:'dkim2_verified']
      else
        self.dkim2_verified = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @verified.nil?
        invalid_properties.push('invalid value for "verified", verified cannot be nil.')
      end

      if @tracking_verified.nil?
        invalid_properties.push('invalid value for "tracking_verified", tracking_verified cannot be nil.')
      end

      if @return_path_verified.nil?
        invalid_properties.push('invalid value for "return_path_verified", return_path_verified cannot be nil.')
      end

      if @dkim1_verified.nil?
        invalid_properties.push('invalid value for "dkim1_verified", dkim1_verified cannot be nil.')
      end

      if @dkim2_verified.nil?
        invalid_properties.push('invalid value for "dkim2_verified", dkim2_verified cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @verified.nil?
      return false if @tracking_verified.nil?
      return false if @return_path_verified.nil?
      return false if @dkim1_verified.nil?
      return false if @dkim2_verified.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] verified Value to be assigned
    def verified=(verified)
      if verified.nil?
        fail ArgumentError, 'verified cannot be nil'
      end

      @verified = verified
    end

    # Custom attribute writer method with validation
    # @param [Object] tracking_verified Value to be assigned
    def tracking_verified=(tracking_verified)
      if tracking_verified.nil?
        fail ArgumentError, 'tracking_verified cannot be nil'
      end

      @tracking_verified = tracking_verified
    end

    # Custom attribute writer method with validation
    # @param [Object] return_path_verified Value to be assigned
    def return_path_verified=(return_path_verified)
      if return_path_verified.nil?
        fail ArgumentError, 'return_path_verified cannot be nil'
      end

      @return_path_verified = return_path_verified
    end

    # Custom attribute writer method with validation
    # @param [Object] dkim1_verified Value to be assigned
    def dkim1_verified=(dkim1_verified)
      if dkim1_verified.nil?
        fail ArgumentError, 'dkim1_verified cannot be nil'
      end

      @dkim1_verified = dkim1_verified
    end

    # Custom attribute writer method with validation
    # @param [Object] dkim2_verified Value to be assigned
    def dkim2_verified=(dkim2_verified)
      if dkim2_verified.nil?
        fail ArgumentError, 'dkim2_verified cannot be nil'
      end

      @dkim2_verified = dkim2_verified
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          verified == o.verified &&
          tracking_verified == o.tracking_verified &&
          return_path_verified == o.return_path_verified &&
          dkim1_verified == o.dkim1_verified &&
          dkim2_verified == o.dkim2_verified
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [verified, tracking_verified, return_path_verified, dkim1_verified, dkim2_verified].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
