=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module GoodSender
  class EmailAccount < ApiModelBase
    # Recipient email address.
    attr_accessor :email

    # Optional display name for the recipient. Used in the To header on the consent email when present, and surfaced through the Dashboard. May be null when no name has been provided.
    attr_accessor :name

    # Domain part of the email address.
    attr_accessor :domain

    # Status of the recipient's consent for receiving emails. 'pending' = awaiting consent email send, 'requested' = consent email dispatched, 'failed' = consent email delivery failed, 'granted' = recipient consented to receive emails, 'denied' = recipient declined to receive emails.
    attr_accessor :consent_status

    # Status of the recipient's engagement with the emails.
    attr_accessor :engagement_status

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'email' => :'email',
        :'name' => :'name',
        :'domain' => :'domain',
        :'consent_status' => :'consentStatus',
        :'engagement_status' => :'engagementStatus'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'email' => :'String',
        :'name' => :'String',
        :'domain' => :'String',
        :'consent_status' => :'String',
        :'engagement_status' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'name',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GoodSender::EmailAccount` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GoodSender::EmailAccount`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      else
        self.domain = nil
      end

      if attributes.key?(:'consent_status')
        self.consent_status = attributes[:'consent_status']
      else
        self.consent_status = nil
      end

      if attributes.key?(:'engagement_status')
        self.engagement_status = attributes[:'engagement_status']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @domain.nil?
        invalid_properties.push('invalid value for "domain", domain cannot be nil.')
      end

      if @consent_status.nil?
        invalid_properties.push('invalid value for "consent_status", consent_status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @email.nil?
      return false if @domain.nil?
      return false if @consent_status.nil?
      consent_status_validator = EnumAttributeValidator.new('String', ["pending", "requested", "failed", "granted", "denied"])
      return false unless consent_status_validator.valid?(@consent_status)
      engagement_status_validator = EnumAttributeValidator.new('String', ["new", "hot", "warm", "cooling", "dormant", "inactive"])
      return false unless engagement_status_validator.valid?(@engagement_status)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] domain Value to be assigned
    def domain=(domain)
      if domain.nil?
        fail ArgumentError, 'domain cannot be nil'
      end

      @domain = domain
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] consent_status Object to be assigned
    def consent_status=(consent_status)
      validator = EnumAttributeValidator.new('String', ["pending", "requested", "failed", "granted", "denied"])
      unless validator.valid?(consent_status)
        fail ArgumentError, "invalid value for \"consent_status\", must be one of #{validator.allowable_values}."
      end
      @consent_status = consent_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] engagement_status Object to be assigned
    def engagement_status=(engagement_status)
      validator = EnumAttributeValidator.new('String', ["new", "hot", "warm", "cooling", "dormant", "inactive"])
      unless validator.valid?(engagement_status)
        fail ArgumentError, "invalid value for \"engagement_status\", must be one of #{validator.allowable_values}."
      end
      @engagement_status = engagement_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          email == o.email &&
          name == o.name &&
          domain == o.domain &&
          consent_status == o.consent_status &&
          engagement_status == o.engagement_status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [email, name, domain, consent_status, engagement_status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
