=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module GoodSender
  # Must provide valid sender and subject. At least one recipient (from 'to', 'cc', or 'bcc') is required. Either 'text_content', 'html_content', 'markdown_content', or 'template_id' is required. When 'markdown_content' is provided, 'text_content' and 'html_content' are ignored. 
  class SendEmail < ApiModelBase
    # Sender address (required)
    attr_accessor :from

    # To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email.
    attr_accessor :to

    # The subject of the email (required)
    attr_accessor :subject

    # Plain text content
    attr_accessor :text_content

    # HTML content
    attr_accessor :html_content

    # Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content. 
    attr_accessor :markdown_content

    # Template ID for templated emails
    attr_accessor :template_id

    # Data to populate template variables
    attr_accessor :template_data

    # Email attachments
    attr_accessor :attachments

    # Custom email headers
    attr_accessor :headers

    # Reply-to address
    attr_accessor :reply_to

    # Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately.
    attr_accessor :send_time

    # Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars.
    attr_accessor :webhook_data

    # Custom tag for tracking. Maximum 100 characters.
    attr_accessor :tag

    # Email tracking settings
    attr_accessor :tracking

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'from' => :'from',
        :'to' => :'to',
        :'subject' => :'subject',
        :'text_content' => :'text_content',
        :'html_content' => :'html_content',
        :'markdown_content' => :'markdown_content',
        :'template_id' => :'template_id',
        :'template_data' => :'template_data',
        :'attachments' => :'attachments',
        :'headers' => :'headers',
        :'reply_to' => :'reply_to',
        :'send_time' => :'send_time',
        :'webhook_data' => :'webhook_data',
        :'tag' => :'tag',
        :'tracking' => :'tracking'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'from' => :'Address',
        :'to' => :'Array<Address>',
        :'subject' => :'String',
        :'text_content' => :'String',
        :'html_content' => :'String',
        :'markdown_content' => :'String',
        :'template_id' => :'String',
        :'template_data' => :'Hash<String, Object>',
        :'attachments' => :'Array<Attachment>',
        :'headers' => :'Hash<String, String>',
        :'reply_to' => :'Address',
        :'send_time' => :'Integer',
        :'webhook_data' => :'Hash<String, String>',
        :'tag' => :'String',
        :'tracking' => :'TrackingSettings'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GoodSender::SendEmail` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GoodSender::SendEmail`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'to')
        if (value = attributes[:'to']).is_a?(Array)
          self.to = value
        end
      else
        self.to = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = ''
      end

      if attributes.key?(:'text_content')
        self.text_content = attributes[:'text_content']
      end

      if attributes.key?(:'html_content')
        self.html_content = attributes[:'html_content']
      end

      if attributes.key?(:'markdown_content')
        self.markdown_content = attributes[:'markdown_content']
      end

      if attributes.key?(:'template_id')
        self.template_id = attributes[:'template_id']
      end

      if attributes.key?(:'template_data')
        if (value = attributes[:'template_data']).is_a?(Hash)
          self.template_data = value
        end
      end

      if attributes.key?(:'attachments')
        if (value = attributes[:'attachments']).is_a?(Array)
          self.attachments = value
        end
      end

      if attributes.key?(:'headers')
        if (value = attributes[:'headers']).is_a?(Hash)
          self.headers = value
        end
      end

      if attributes.key?(:'reply_to')
        self.reply_to = attributes[:'reply_to']
      end

      if attributes.key?(:'send_time')
        self.send_time = attributes[:'send_time']
      end

      if attributes.key?(:'webhook_data')
        if (value = attributes[:'webhook_data']).is_a?(Hash)
          self.webhook_data = value
        end
      end

      if attributes.key?(:'tag')
        self.tag = attributes[:'tag']
      end

      if attributes.key?(:'tracking')
        self.tracking = attributes[:'tracking']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if @to.nil?
        invalid_properties.push('invalid value for "to", to cannot be nil.')
      end

      if @subject.nil?
        invalid_properties.push('invalid value for "subject", subject cannot be nil.')
      end

      if !@markdown_content.nil? && @markdown_content.to_s.length < 1
        invalid_properties.push('invalid value for "markdown_content", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @from.nil?
      return false if @to.nil?
      return false if @subject.nil?
      return false if !@markdown_content.nil? && @markdown_content.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] from Value to be assigned
    def from=(from)
      if from.nil?
        fail ArgumentError, 'from cannot be nil'
      end

      @from = from
    end

    # Custom attribute writer method with validation
    # @param [Object] to Value to be assigned
    def to=(to)
      if to.nil?
        fail ArgumentError, 'to cannot be nil'
      end

      @to = to
    end

    # Custom attribute writer method with validation
    # @param [Object] subject Value to be assigned
    def subject=(subject)
      if subject.nil?
        fail ArgumentError, 'subject cannot be nil'
      end

      @subject = subject
    end

    # Custom attribute writer method with validation
    # @param [Object] markdown_content Value to be assigned
    def markdown_content=(markdown_content)
      if markdown_content.nil?
        fail ArgumentError, 'markdown_content cannot be nil'
      end

      if markdown_content.to_s.length < 1
        fail ArgumentError, 'invalid value for "markdown_content", the character length must be greater than or equal to 1.'
      end

      @markdown_content = markdown_content
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          from == o.from &&
          to == o.to &&
          subject == o.subject &&
          text_content == o.text_content &&
          html_content == o.html_content &&
          markdown_content == o.markdown_content &&
          template_id == o.template_id &&
          template_data == o.template_data &&
          attachments == o.attachments &&
          headers == o.headers &&
          reply_to == o.reply_to &&
          send_time == o.send_time &&
          webhook_data == o.webhook_data &&
          tag == o.tag &&
          tracking == o.tracking
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [from, to, subject, text_content, html_content, markdown_content, template_id, template_data, attachments, headers, reply_to, send_time, webhook_data, tag, tracking].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
