# -*- encoding: utf-8 -*-

=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "goodsender/version"

Gem::Specification.new do |s|
  s.name        = "goodsender"
  s.version     = GoodSender::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["GoodSender"]
  s.email       = ["support@goodsender.com"]
  s.homepage    = "https://github.com/good-sender/ruby-sdk"
  s.summary     = "Official GoodSender API client for Ruby"
  s.description = "Ruby SDK for the GoodSender API."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
