=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

module GoodSender
  VERSION = '0.1.0'
end
