=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GoodSender::DomainsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DomainsApi' do
  before do
    # run before each test
    @api_instance = GoodSender::DomainsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainsApi' do
    it 'should create an instance of DomainsApi' do
      expect(@api_instance).to be_instance_of(GoodSender::DomainsApi)
    end
  end

  # unit tests for list_domains
  # List domains
  # Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of records to return.
  # @option opts [String] :cursor Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response.
  # @return [DomainListResponse]
  describe 'list_domains test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
