=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GoodSender::EmailsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EmailsApi' do
  before do
    # run before each test
    @api_instance = GoodSender::EmailsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmailsApi' do
    it 'should create an instance of EmailsApi' do
      expect(@api_instance).to be_instance_of(GoodSender::EmailsApi)
    end
  end

  # unit tests for get_email_consent_status
  # Get recipient consent status
  # Retrieve the current consent status for an email address. Optionally filter by sender domain.
  # @param email Email address to look up.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain Optional sender domain to filter consent records by. When omitted, returns consent across all domains.
  # @return [Array<EmailAccount>]
  describe 'get_email_consent_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_email_consents
  # List email consent statuses
  # Retrieve a paginated list of email consent statuses for a domain.
  # @param domain Sender domain to filter consent records by.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of records to return.
  # @option opts [String] :cursor Cursor for pagination.
  # @option opts [String] :consent_status Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails.
  # @option opts [String] :engagement_status Status of the recipient&#39;s engagement with the emails.
  # @return [EmailListResponse]
  describe 'list_email_consents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for request_email_consent
  # Request recipients&#39; consent to receive emails from your domain
  # Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
  # @param consent_email_request 
  # @param [Hash] opts the optional parameters
  # @return [ConsentEmailResult]
  describe 'request_email_consent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_email
  # Send an email or a batch of emails
  # Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
  # @param send_email_request List of emails to send
  # @param [Hash] opts the optional parameters
  # @return [SendEmailResponse]
  describe 'send_email test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_template_email
  # Send a transactional email using a template
  # Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
  # @param template_email_request Template email to send
  # @param [Hash] opts the optional parameters
  # @return [TemplateEmailResponse]
  describe 'send_template_email test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
