=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GoodSender::EmailAccount
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoodSender::EmailAccount do
  #let(:instance) { GoodSender::EmailAccount.new }

  describe 'test an instance of EmailAccount' do
    it 'should create an instance of EmailAccount' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GoodSender::EmailAccount)
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "domain"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "consent_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["pending", "requested", "failed", "granted", "denied"])
      # validator.allowable_values.each do |value|
      #   expect { instance.consent_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "engagement_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["new", "hot", "warm", "cooling", "dormant", "inactive"])
      # validator.allowable_values.each do |value|
      #   expect { instance.engagement_status = value }.not_to raise_error
      # end
    end
  end

end
