=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GoodSender::TrackingSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoodSender::TrackingSettings do
  #let(:instance) { GoodSender::TrackingSettings.new }

  describe 'test an instance of TrackingSettings' do
    it 'should create an instance of TrackingSettings' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GoodSender::TrackingSettings)
    end
  end

  describe 'test attribute "opens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "clicks"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "unsubscribes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "unsubscribe_group_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
