=begin
#Goodsender API

#Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

The version of the OpenAPI document: 1.0.0
Contact: support@goodsender.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

# Common files
require 'goodsender/api_client'
require 'goodsender/api_error'
require 'goodsender/api_model_base'
require 'goodsender/version'
require 'goodsender/configuration'

# Models
require 'goodsender/models/address'
require 'goodsender/models/attachment'
require 'goodsender/models/consent_email_entry'
require 'goodsender/models/consent_email_recipient'
require 'goodsender/models/consent_email_request'
require 'goodsender/models/consent_email_result'
require 'goodsender/models/domain'
require 'goodsender/models/domain_list_response'
require 'goodsender/models/domain_verification'
require 'goodsender/models/email_account'
require 'goodsender/models/email_list_response'
require 'goodsender/models/error_response'
require 'goodsender/models/quota_exceeded_error'
require 'goodsender/models/send_email'
require 'goodsender/models/send_email_error_response'
require 'goodsender/models/send_email_request'
require 'goodsender/models/send_email_response'
require 'goodsender/models/template_email_request'
require 'goodsender/models/template_email_request_template'
require 'goodsender/models/template_email_response'
require 'goodsender/models/tracking_settings'

# APIs
require 'goodsender/api/domains_api'
require 'goodsender/api/emails_api'

module GoodSender
  class << self
    # Customize default settings for the SDK using block.
    #   GoodSender.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
